### ISSUE TITLE
Lack of death fade on RC freezes/glitches animation of the corpse

### ISSUE THREAD

**Issue by freghar** [zen-mod/ZEN#556]
**Arma 3 Version:** `2.00` (stable)
**CBA Version:** `3.15.1` (stable)
**ZEN Version:** `1.9.0` (stable)

**Mods:**
```
- CBA_A3
- ZEN
- ACE3
- A lot (~40) of other content mods, likely not important, reproducible with vanilla too.
```

**Description:**
ZEN seems to remove the "death fade" a remote controlled unit would normally have in vanilla Curator. This causes an immediate switch Curator UI on death of the controlled unit. Since the unit was local to the client with assigned Curator, and that client is frozen until the UI loads, this causes the unit to be often stuck in a standing (or similar) animation, before the client owner can un-freeze and resume / reset the animation and let the unit fall to ground.
Sometimes, the unit falls to ground first, and then glitches into a standing animation before falling to ground again upon opening the Curator UI.

This is a much bigger issue in modded games where the Curator interface can take 10+ seconds to load and while this will be fixed with next Arma 3 stable, the issue still remains - it will only take a shorter time for the unit to fall to ground.

My guess is that this is caused by the soldier unit owner being frozen, as it doesn't happen with vanilla Curator or Achilles where the death fade plays out. The solution is thus to either re-add the camera fade back, or to somehow wait a frame or two before switching back to the Curator UI (haven't tested how long you need to wait, actually).

**Expected behavior:**
A remote controlled unit falls to the ground upon death, as expected.

**Steps to reproduce:**
1. Have 2 players in a mission, one of them with assigned Curator.
1. Have the Curator player open up the UI, spawn a soldier unit and remote control it.
1. Have the second player shoot and kill the RCd soldier.
1. The second player should observer either
   1. The soldier going down in a typical ragdoll animation, glitching when the Curator player's UI re-opens.
   1. The soldier standing up (and ignoring further bullets), possibly in a broken animation, and glitching + going down when the Curator player's UI re-opens.

**Where did the issue occur?**
- Dedicated

**Comment by JamesTheClarke** [comment]
Can confirm this issue, I hope the devs can fix it because it makes RC outside of roleplaying a bit immersion-breaking and is a dead giveaway that Zeus was hiding amongst the AI group the players just engaged.

**Comment by fire-391** [comment]
This should be fixed in Arma version 2.02, is currently fixed on Prof/perf branch. In the mean time check out Arma Zeus cache mod by Dedmen. We use this mod and have not had this problem.

**Comment by mharis001** [comment]
As @fire-391 commented, this issue should be resolved with Arma 2,02. We can leave the issue open until then and investigate if the problem persists.

**Comment by freghar** [comment]
I mentioned this in my original report already - I don't think the core issue itself is fixed on 2.02, unless something more fundamental changed in how the engine threads handle work.

However actually testing it on Dev, the difference between a remote controlled unit and a non-remote-controlled one is no longer clearly perceivable, so while the issue might be still there, it's not realistically noticeable anymore.

**Comment by mharis001** [comment]
Arma 3 2.02 is out now and contains the improvements to Zeus display loading times. Is this still an issue?

**Comment by freghar** [comment]
It's still the same as it was on devbranch a few weeks ago - I'm not sure whether the underlying problem was fixed, but it's not practically perceptible anymore.
